name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          output: dist/github-snake.svg

      - name: Upload the snake animation
        uses: actions/upload-artifact@v2
        with:
          name: github-snake
          path: dist/github-snake.svg
